export const INITIAL_TICKETS = [
  {
    id: "NAG-8472",
    summary: "Contaminated drinking water supply in municipal pipeline",
    details: "Brown murky sewage backflow reported by 18 households. Severe public health risk.",
    category: "Water Supply & Sanitation",
    location: "Ulsoor Bazaar, Ward 112",
    ward: "112 - Domlur / Indiranagar",
    department: "BWSSB",
    urgency: "Critical",
    slaStatus: "breached",
    slaRemaining: "Breached (+4h 12m)",
    slaDeadline: "2025-02-18T10:00:00",
    createdAt: "2025-02-18 06:14 AM",
    timestamp: 1739840040000,
    assignedOfficer: "Eng. Suresh Patil",
    escalated: false,
    resolutionTimeframe: "Within 24 Hours",
    statusText: "Immediate Intervention Required"
  },
  {
    id: "NAG-8473",
    summary: "High-tension live wire snapped and dangling near school gate",
    details: "11kV distribution line hanging 4 feet from ground level on 8th Cross road.",
    category: "Electricity & Streetlights",
    location: "Malleshwaram 8th Cross, Ward 45",
    ward: "45 - Malleshwaram Central",
    department: "BESCOM",
    urgency: "Critical",
    slaStatus: "breached",
    slaRemaining: "Breached (+1h 30m)",
    slaDeadline: "2025-02-18T12:00:00",
    createdAt: "2025-02-18 08:30 AM",
    timestamp: 1739848200000,
    assignedOfficer: "Lineman K. Raghu",
    escalated: false,
    resolutionTimeframe: "Immediate / 4 Hours",
    statusText: "Hazardous Live Line Alert"
  },
  {
    id: "NAG-8474",
    summary: "Deep crater-sized pothole on arterial flyover ramp",
    details: "Ramp connecting Outer Ring Road causing two-wheeler accidents during peak transit hours.",
    category: "Roads & Infrastructure",
    location: "Marathahalli Flyover, Ward 85",
    ward: "85 - Doddanekkundi",
    department: "BBMP Works",
    urgency: "High",
    slaStatus: "approaching",
    slaRemaining: "1h 15m remaining",
    slaDeadline: "2025-02-18T16:00:00",
    createdAt: "2025-02-18 09:45 AM",
    timestamp: 1739852700000,
    assignedOfficer: "Asst. Exec. Eng. Ramesh Babu",
    escalated: false,
    resolutionTimeframe: "Within 48 Hours",
    statusText: "Crew Dispatched for Cold Mix Patch"
  },
  {
    id: "NAG-8475",
    summary: "Commercial garbage dumping blocking stormwater drain canal",
    details: "Hotel banquet waste bags obstructing Rajakaluve inlet ahead of forecasted rains.",
    category: "Solid Waste Management",
    location: "Koramangala 4th Block, Ward 151",
    ward: "151 - Koramangala East",
    department: "BBMP SWM",
    urgency: "High",
    slaStatus: "approaching",
    slaRemaining: "1h 50m remaining",
    slaDeadline: "2025-02-18T17:00:00",
    createdAt: "2025-02-18 10:10 AM",
    timestamp: 1739854200000,
    assignedOfficer: "Health Inspector N. Manjunath",
    escalated: false,
    resolutionTimeframe: "Within 24 Hours",
    statusText: "JCB Excavator Requested"
  },
  {
    id: "NAG-8476",
    summary: "Major drinking water main burst flooding residential street",
    details: "600mm treated water pipeline ruptured; water gushing into basements.",
    category: "Water Supply & Sanitation",
    location: "Indiranagar 12th Main, Ward 112",
    ward: "112 - Domlur / Indiranagar",
    department: "BWSSB",
    urgency: "Critical",
    slaStatus: "on-track",
    slaRemaining: "7h 40m remaining",
    slaDeadline: "2025-02-18T22:00:00",
    createdAt: "2025-02-18 11:20 AM",
    timestamp: 1739858400000,
    assignedOfficer: "Mobile Tanker Response Unit 4",
    escalated: false,
    resolutionTimeframe: "Within 24 Hours",
    statusText: "Isolation Valves Shut - Crew On-Site"
  },
  {
    id: "NAG-8477",
    summary: "Streetlights non-functional across entire 14th Main stretch",
    details: "Cluster of 16 sodium-vapor and LED luminaires offline for two consecutive nights.",
    category: "Electricity & Streetlights",
    location: "HSR Layout Sector 2, Ward 174",
    ward: "174 - HSR Sector 2",
    department: "BESCOM",
    urgency: "Medium",
    slaStatus: "on-track",
    slaRemaining: "18h 30m remaining",
    slaDeadline: "2025-02-19T08:00:00",
    createdAt: "2025-02-18 12:05 PM",
    timestamp: 1739861100000,
    assignedOfficer: "Contractor M/s Shanti Electricals",
    escalated: false,
    resolutionTimeframe: "Within 36 Hours",
    statusText: "Scheduled for Night Shift Maintenance"
  },
  {
    id: "NAG-8478",
    summary: "Pack of aggressive stray dogs near kindergarten playground",
    details: "Citizens requesting vaccination and animal birth control (ABC) squad visit.",
    category: "Public Health & Safety",
    location: "Jayanagar 4th T Block, Ward 168",
    ward: "168 - Jayanagar 4th T",
    department: "Health & Safety",
    urgency: "Medium",
    slaStatus: "on-track",
    slaRemaining: "22h 10m remaining",
    slaDeadline: "2025-02-19T11:00:00",
    createdAt: "2025-02-18 01:15 PM",
    timestamp: 1739865300000,
    assignedOfficer: "Dr. P. Venkatesh (Vet Officer)",
    escalated: false,
    resolutionTimeframe: "Within 48 Hours",
    statusText: "Animal Welfare Squad Queued"
  },
  {
    id: "NAG-8479",
    summary: "Fallen tree branch blocking two lanes of public transit bus stop",
    details: "Old Gulmohar tree limb snapped after strong winds; blocking BMTC bus bay.",
    category: "Roads & Infrastructure",
    location: "MG Road Metro Junction, Ward 111",
    ward: "111 - Shantala Nagar",
    department: "BBMP Works",
    urgency: "High",
    slaStatus: "on-track",
    slaRemaining: "5h 25m remaining",
    slaDeadline: "2025-02-18T19:00:00",
    createdAt: "2025-02-18 01:35 PM",
    timestamp: 1739866500000,
    assignedOfficer: "Forestry Dept Quick Action Team",
    escalated: false,
    resolutionTimeframe: "Within 8 Hours",
    statusText: "Chainsaw Team En-Route"
  },
  {
    id: "NAG-8480",
    summary: "Overflowing municipal wet waste compactor bin emitting stench",
    details: "Secondary collection bin not cleared for 48 hours; encroaching footpath.",
    category: "Solid Waste Management",
    location: "BTM Layout 2nd Stage, Ward 176",
    ward: "176 - BTM Layout",
    department: "BBMP SWM",
    urgency: "Medium",
    slaStatus: "approaching",
    slaRemaining: "45m remaining",
    slaDeadline: "2025-02-18T15:00:00",
    createdAt: "2025-02-18 02:15 PM",
    timestamp: 1739868900000,
    assignedOfficer: "Supervisor Ganesh M.",
    escalated: false,
    resolutionTimeframe: "Within 12 Hours",
    statusText: "Compactor Truck Rerouted"
  },
  {
    id: "NAG-8481",
    summary: "Uncovered underground drainage (UGD) manhole on busy footpath",
    details: "Missing cast iron lid poses mortal danger to pedestrians and visually impaired.",
    category: "Water Supply & Sanitation",
    location: "Commercial Street, Ward 110",
    ward: "110 - Sampangiram Nagar",
    department: "BWSSB",
    urgency: "Critical",
    slaStatus: "breached",
    slaRemaining: "Breached (+2h 55m)",
    slaDeadline: "2025-02-18T11:30:00",
    createdAt: "2025-02-18 07:15 AM",
    timestamp: 1739843700000,
    assignedOfficer: "Sub-Divisional Eng. L. Murthy",
    escalated: false,
    resolutionTimeframe: "Immediate / 4 Hours",
    statusText: "Safety Barricade Pending"
  }
];

// Department statistics for Recharts
export const DEPARTMENT_STATS = [
  { department: "BBMP Works", count: 116, resolvedRate: 88, color: "#2563EB" },
  { department: "BWSSB", count: 96, resolvedRate: 92, color: "#0284C7" },
  { department: "BESCOM", count: 62, resolvedRate: 95, color: "#D97706" },
  { department: "BBMP SWM", count: 41, resolvedRate: 84, color: "#059669" },
  { department: "Health & Safety", count: 27, resolvedRate: 91, color: "#7C3AED" },
];

export const QUICK_PROMPTS = [
  {
    label: "Water Shortage",
    icon: "🚰",
    text: "Severe drinking water shortage in HAL 2nd Stage, Indiranagar. The municipal pipeline has zero pressure since yesterday morning.",
    category: "Water Supply & Sanitation",
    department: "BWSSB"
  },
  {
    label: "Road Pothole Hazard",
    icon: "🚧",
    text: "Large, dangerous pothole near Metro Pillar 142 on Outer Ring Road causing heavy traffic jams and two-wheeler skidding.",
    category: "Roads & Infrastructure",
    department: "BBMP Works"
  },
  {
    label: "Streetlights Out",
    icon: "💡",
    text: "Entire lane of streetlights not working in HSR Layout Sector 3 for the past 4 nights. Area is completely dark and unsafe.",
    category: "Electricity & Streetlights",
    department: "BESCOM"
  },
  {
    label: "Garbage Dump",
    icon: "🗑️",
    text: "Overflowing garbage dump and construction debris blocking the footpath outside Community Hall in Koramangala 4th Block.",
    category: "Solid Waste Management",
    department: "BBMP SWM"
  }
];
